title: "Vosk Speech-to-Text API Service"
description: "Deploy a Vosk STT API service on OCI - Simple deployment for personal use"
schemaVersion: 1.1.0
version: "20250817-simplified"
locale: "en"

informationalText: |
  一鍵部署 Vosk Speech-to-Text API 服務到 Oracle Cloud Infrastructure
  支持 Free Tier，提供多語言語音轉文字功能

variableGroups:
  - title: "基本配置"
    visible: true
    variables:
      - compartment_id
      - availability_domain
      - api_key
      - ssh_authorized_keys

  - title: "機器規格 (Free Tier)"
    visible: true
    variables:
      - vm_shape
      - vm_ocpus
      - vm_memory_gb

variables:
  # Basic Configuration
  compartment_id:
    type: oci:identity:compartment:id
    title: "區間"
    description: "選擇用於部署資源的區間"
    required: true

  availability_domain:
    type: oci:identity:availabilitydomain:name
    title: "可用性網域"
    description: "選擇部署的可用性網域"
    dependsOn:
      compartmentId: compartment_id
    required: true

  api_key:
    type: password
    title: "API 金鑰"
    description: "語音轉文字服務的安全金鑰（至少16個字元）"
    required: true
    minLength: 16
    maxLength: 128
    pattern: "^[a-zA-Z0-9_-]+$"

  ssh_authorized_keys:
    type: oci:core:ssh:publickey
    title: "SSH 公鑰 (可選)"
    description: "用於 SSH 連接的公鑰。留空將禁用 SSH 訪問。"
    required: false

  # Machine Configuration
  vm_shape:
    type: enum
    title: "機器規格"
    description: "選擇機器規格。免費方案建議：E2.1.Micro (1核心/1GB) 或 A1.Flex (最多4核心/24GB)"
    required: true
    default: "VM.Standard.A1.Flex"
    enum:
      - "VM.Standard.E2.1.Micro"
      - "VM.Standard.A1.Flex" 
      - "VM.Standard.E3.Flex"
      - "VM.Standard.E4.Flex"

  vm_ocpus:
    type: integer
    title: "CPU 核心數"
    description: "彈性機器規格的 CPU 核心數。免費方案 A1.Flex 最多 4 核心"
    minimum: 1
    maximum: 8
    default: 2
    visible:
      or:
        - eq: [vm_shape, "VM.Standard.E3.Flex"]
        - eq: [vm_shape, "VM.Standard.E4.Flex"]
        - eq: [vm_shape, "VM.Standard.A1.Flex"]

  vm_memory_gb:
    type: integer
    title: "記憶體 (GB)"
    description: "彈性機器規格的記憶體大小。免費方案 A1.Flex 最多 24GB，建議至少 8GB"
    minimum: 6
    maximum: 24
    default: 8
    visible:
      or:
        - eq: [vm_shape, "VM.Standard.E3.Flex"]
        - eq: [vm_shape, "VM.Standard.E4.Flex"]
        - eq: [vm_shape, "VM.Standard.A1.Flex"]

outputs:
  deployment_info:
    type: json
    title: "部署資訊"
    displayText: "部署完成後的服務資訊"
    visible: true