title: "Vosk Speech-to-Text API Service"
description: "Deploy a complete Vosk-based Speech-to-Text API service on OCI Free Tier"
schemaVersion: 1.1.0
version: "20240817"
locale: "en"

informationalText: |
  This template deploys a Vosk Speech-to-Text API service on Oracle Cloud Infrastructure.
  The service provides RESTful endpoints for audio transcription with support for multiple
  languages and formats. Designed for OCI Free Tier deployment.

variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
      - tenancy_ocid
      - region
      - compute_image_strategy_enum
      - network_strategy_enum

  - title: "Required Configuration"
    visible: true
    variables:
      - compute_compartment_ocid
      - network_compartment_ocid
      - availability_domain
      - api_key

  - title: "Network Strategy"
    visible: true
    variables:
      - network_strategy
      - vcn_id
      - subnet_id

  - title: "Instance Configuration"
    visible: true
    variables:
      - vm_shape
      - vm_ocpus
      - vm_memory_gb
      - compute_image_strategy
      - operating_system
      - platform_image_ocid
      - custom_image_ocid
      - ssh_authorized_keys

variables:
  ######################################################
  ##############      HIDDEN VARIABLES      ###########
  ######################################################
  
  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  compute_image_strategy_enum:
    type: map(any)
    default:
      PLATFORM_IMAGE: "Platform Image"
      CUSTOM_IMAGE: "Custom Image"

  network_strategy_enum:
    type: map(any)
    default:
      CREATE_NEW_VCN: "Create New VCN and Subnet"
      USE_EXISTING_VCN: "Use Existing VCN and Subnet"

  ######################################################
  ##############    SERVICE VARIABLES       ###########
  ######################################################

  api_key:
    type: password
    title: "API Key"
    description: "Secure API key for the STT service (minimum 16 characters, alphanumeric and hyphens only)"
    required: true
    minLength: 16
    maxLength: 128
    pattern: "^[a-zA-Z0-9_-]+$"

  ######################################################
  ##############    COMPUTE VARIABLES       ###########
  ######################################################

  compute_compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compute Compartment"
    description: "The compartment in which to create compute resources. Ensure you have 'manage compute-family' permissions."
    required: true
    default: compartment_ocid

  network_compartment_ocid:
    type: oci:identity:compartment:id
    title: "Network Compartment"
    description: "The compartment for network resources. Ensure you have 'manage virtual-network-family' permissions. Can be same as compute compartment."
    required: true
    default: compartment_ocid

  availability_domain:
    type: oci:identity:availabilitydomain:name
    title: "Availability Domain"
    description: "The availability domain for the compute instance"
    dependsOn:
      regionName: region
      compartmentId: compute_compartment_ocid
    required: true

  api_key:
    type: password
    title: "API Key"
    description: "Secure API key for the STT service (minimum 16 characters, alphanumeric and hyphens only)"
    required: true
    minLength: 16
    maxLength: 128
    pattern: "^[a-zA-Z0-9_-]+$"

  ######################################################
  ##############    NETWORK STRATEGY        ###########
  ######################################################

  network_strategy:
    type: enum
    title: "Network Strategy"
    description: |
      Choose your network deployment strategy:
      • "Use Existing VCN" - Select if you have existing VCN (avoids permission issues)
      • "Create New VCN" - Creates new VCN (requires network permissions)
      • "Create Minimal VCN" - Creates minimal VCN for Free Tier (recommended for new accounts)
    enum:
      - "Use Existing VCN and Subnet"
      - "Create New VCN and Subnet"
      - "Create Minimal VCN and Subnet"
    required: true
    default: "Create Minimal VCN and Subnet"

  vcn_id:
    type: oci:core:vcn:id
    title: "Existing VCN"
    description: "Select an existing VCN with internet access"
    dependsOn:
      compartmentId: network_compartment_ocid
    visible:
      eq:
        - network_strategy
        - "Use Existing VCN and Subnet"
    required: true

  subnet_id:
    type: oci:core:subnet:id
    title: "Existing Public Subnet"
    description: "Select an existing public subnet with internet gateway access"
    dependsOn:
      compartmentId: network_compartment_ocid
      vcnId: vcn_id
      hidePrivateSubnet: true
    visible:
      eq:
        - network_strategy
        - "Use Existing VCN and Subnet"
    required: true

  ######################################################
  ##############    PERMISSION HELP         ###########
  ######################################################

  permission_help_text:
    type: string
    title: "Permission Requirements"
    description: |
      Required IAM permissions by strategy:
      
      For "Use Existing VCN":
      • manage instances in compartment
      • use virtual-network-family in compartment
      
      For "Create New VCN" or "Create Minimal VCN":
      • manage virtual-network-family in compartment
      • manage instances in compartment
      
      If deployment fails with permission errors, contact your OCI administrator
      or try a different network strategy.
    visible: true
    default: ""
    required: false

  # Instance Configuration
  vm_shape:
    type: enum
    title: "Instance Shape"
    description: "Choose compute instance shape. Free Tier options: E2.1.Micro (1 OCPU/1GB) or A1.Flex (4 OCPU/24GB)."
    required: true
    default: "VM.Standard.A1.Flex"
    enum:
      - "VM.Standard.E2.1.Micro"
      - "VM.Standard.A1.Flex" 
      - "VM.Standard.E2.2"
      - "VM.Standard.E3.Flex"
      - "VM.Standard.E4.Flex"

  vm_ocpus:
    type: integer
    title: "OCPUs"
    description: "Number of OCPUs for flexible shapes. Free Tier A1.Flex: up to 4 OCPUs always free."
    minimum: 1
    maximum: 64
    default: 2
    visible:
      or:
        - eq:
          - vm_shape
          - "VM.Standard.E3.Flex"
        - eq:
          - vm_shape
          - "VM.Standard.E4.Flex"
        - eq:
          - vm_shape
          - "VM.Standard.A1.Flex"

  vm_memory_gb:
    type: integer
    title: "Memory (GB)"
    description: "Memory in GB for flexible shapes. Free Tier A1.Flex: up to 24 GB always free. Minimum 6 GB recommended for STT."
    minimum: 1
    maximum: 1024
    default: 8
    visible:
      or:
        - eq:
          - vm_shape
          - "VM.Standard.E3.Flex"
        - eq:
          - vm_shape
          - "VM.Standard.E4.Flex"
        - eq:
          - vm_shape
          - "VM.Standard.A1.Flex"

  # Image Configuration
  compute_image_strategy:
    type: enum
    title: "Image Strategy"
    description: "Choose between Platform Images or Custom Images"
    required: true
    default: "Platform Image"
    enum:
      - "Platform Image"
      - "Custom Image"

  operating_system:
    type: enum
    title: "Operating System"
    description: "Choose the operating system for Platform Images"
    required: true
    default: "Oracle Linux"
    visible:
      eq:
        - compute_image_strategy
        - "Platform Image"
    enum:
      - "Oracle Linux"
      - "Ubuntu"
      - "CentOS"

  platform_image_ocid:
    type: oci:core:image:id
    title: "Platform Image"
    description: "Select a Platform Image based on the Operating System choice"
    dependsOn:
      compartmentId: compartment_id
      operatingSystem: operating_system
    visible:
      eq:
        - compute_image_strategy
        - "Platform Image"
    required: true

  custom_image_ocid:
    type: oci:core:image:id
    title: "Custom Image"
    description: "Select your custom image OCID (should be based on Oracle Linux 8+)"
    dependsOn:
      compartmentId: compartment_id
    visible:
      eq:
        - compute_image_strategy
        - "Custom Image"
    required: true

  # Network Configuration
  create_vcn:
    type: boolean
    title: "Create New VCN"
    description: "Create a new Virtual Cloud Network and subnet. If you encounter permission errors, try using an existing VCN instead."
    default: true

  vcn_id:
    type: oci:core:vcn:id
    title: "Existing VCN"
    description: "Select an existing VCN with internet access. This option avoids VCN creation permission requirements."
    dependsOn:
      compartmentId: compartment_id
    visible:
      eq:
        - create_vcn
        - false
    required: true

  subnet_id:
    type: oci:core:subnet:id
    title: "Existing Public Subnet"
    description: "Select an existing public subnet with internet gateway access for API accessibility."
    dependsOn:
      compartmentId: compartment_id
      vcnId: vcn_id
    visible:
      eq:
        - create_vcn
        - false
    required: true

  # Advanced Settings
  region:
    type: oci:identity:region:name
    title: "Region"
    description: "OCI region for deployment"
    required: true

  image_id:
    type: string
    title: "Custom Image ID"
    description: "Custom OS image ID (leave empty for auto-detection)"
    required: false

  docker_image_name:
    type: string
    title: "Docker Image Name"
    description: "Docker image name for the STT API"
    default: "vosk-stt-api:latest"
    required: false

  github_repo_url:
    type: string
    title: "GitHub Repository URL"
    description: "GitHub repository URL for the project source code"
    default: "https://github.com/kouko/oci-vosk-speech2text-api-service.git"
    required: false

  # Hidden enum definitions
  compute_image_strategy_enum:
    type: map
    default:
      PLATFORM_IMAGE: "Platform Image"
      CUSTOM_IMAGE: "Custom Image"

outputs:
  instance_public_ip:
    title: "Instance Public IP"
    description: "Public IP address of the deployed instance"
    type: link

  api_url:
    title: "API URL"
    description: "URL to access the STT API"
    type: link

  api_docs_url:
    title: "API Documentation"
    description: "URL to access the API documentation"
    type: link

  deployment_info:
    title: "Deployment Information"
    description: "Complete deployment information and commands"
    type: json